steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/fleet-repo/fleet-app:$COMMIT_SHA"
      - "."

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "us-central1-docker.pkg.dev/$PROJECT_ID/fleet-repo/fleet-app:$COMMIT_SHA"

  - name: gcr.io/cloud-builders/gcloud
    args:
      - deploy
      - releases
      - create
      - "release-$COMMIT_SHA"
      - "--delivery-pipeline=fleet-app-pipeline"
      - "--region=us-central1"
      - "--images=fleet-app=us-central1-docker.pkg.dev/$PROJECT_ID/fleet-repo/fleet-app:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: "us-central1"
