options:
logging: CLOUD_LOGGING_ONLY
substitutions:
_ARTIFACT_REPO: "us-central1-docker.pkg.dev/$PROJECT_ID/fleet-platform-repo"


steps:
# 1) Lint & Unit tests (optional but recommended)
- name: 'python:3.11'
id: 'unit-tests'
entrypoint: 'bash'
args:
- -c
- |
pip install -r requirements.txt
pip install pytest
pytest -q || exit 1


# 2) Build image
- name: 'gcr.io/cloud-builders/docker'
id: 'build-image'
args: [
'build',
'-t', '$_ARTIFACT_REPO/fleet-api:$SHORT_SHA',
'.'
]


# 3) Push image
- name: 'gcr.io/cloud-builders/docker'
id: 'push-image'
args: [
'push',
'$_ARTIFACT_REPO/fleet-api:$SHORT_SHA'
]


# 4) (Optional) Run migrations -- requires Cloud SQL setup or a separate step in deployment
# Uncomment and adapt if you can run migrations during build (usually run in deploy stage)
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
# id: 'migrate'
# entrypoint: 'bash'
# args: ['-c', 'gcloud sql connect $DB_INSTANCE --user=$DB_USER --quiet --command="psql ..."']


# 5) Create Cloud Deploy release
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
id: 'create-release'
entrypoint: 'bash'
args:
- -c
- |
gcloud deploy releases create "release-$SHORT_SHA" \
--project="$PROJECT_ID" \
--delivery-pipeline="fleet-pipeline" \
timeout: '1200s'